// Legal content templates for investment documents

export function getEquityTerms(ownership: number) {
  return `
3. INVESTMENT TERMS - EQUITY TOKENIZATION

3.1 OWNERSHIP STRUCTURE
The Investor acquires ${ownership.toFixed(4)}% fractional ownership of the Property through digital tokens representing equity interest. Each token confers:

(a) Proportional ownership rights in the underlying Property
(b) Voting rights in property governance decisions proportional to token holdings
(c) Rights to receive proportional dividends from rental income and capital appreciation
(d) Rights to participate in major property decisions via governance proposals

3.2 DIVIDEND DISTRIBUTION
Dividends shall be distributed quarterly (or as determined by actual property income) in proportion to token holdings. Distribution is subject to:
- Property generating positive net rental income after expenses
- Retention of reasonable reserves for maintenance and emergencies
- Approval of distribution amount by token holder vote if required

3.3 VOTING RIGHTS
Token holders may vote on governance proposals including:
- Major maintenance and renovation projects exceeding threshold amounts
- Property sale or refinancing decisions
- Changes to property management
- Distribution policy modifications
Each token grants one vote. Proposals require majority approval unless otherwise specified.

3.4 TRANSFER RIGHTS
Tokens may be transferred to other KYC-verified investors subject to:
- Compliance with Nigerian securities regulations
- Right of first refusal by existing token holders (if applicable)
- Platform transfer mechanisms and applicable fees
`;
}

export function getDebtTerms(interestRate: number, duration: number) {
  return `
3. INVESTMENT TERMS - DEBT TOKENIZATION

3.1 LOAN STRUCTURE
The Investor provides debt financing secured against the Property. This is a fixed-income investment where tokens represent debt obligations of the property owner.

3.2 INTEREST PAYMENTS
Interest shall be paid at ${interestRate}% per annum, calculated monthly and distributed quarterly.
Payment is secured by:
- First charge on the Property
- Personal guarantee of property owner (if applicable)
- Property rental income assignment

3.3 REPAYMENT SCHEDULE
Principal repayment: ${duration} months from investment date
Early repayment: Permitted with 30 days notice, no penalty
Default provisions: Detailed in Section 7 below

3.4 SECURITY AND COLLATERAL
This investment is secured by registered charge over the Property with priority ranking over other creditors (subject to existing liens disclosed).
`;
}

export function getRevenueShareTerms(revenuePercentage: number, duration: number) {
  return `
3. INVESTMENT TERMS - REVENUE SHARE TOKENIZATION

3.1 REVENUE SHARING STRUCTURE
The Investor receives ${revenuePercentage}% of gross rental revenue generated by the Property for a period of ${duration} months.

3.2 DISTRIBUTION TERMS
Revenue distributions occur monthly within 15 business days of month-end.
Minimum distribution threshold: ₦10,000 per period
Distributions below threshold carried forward to next period

3.3 DURATION AND TERMINATION
Revenue sharing period: ${duration} months from first rental payment
No ownership rights or capital appreciation participation
Arrangement terminates automatically at end of period or upon property sale

3.4 REVENUE CALCULATION
Revenue share calculated on gross rental income before deducting:
- Property management fees
- Maintenance costs
- Property taxes
Investor bears no operational expenses.
`;
}

export function getRightsAndObligations() {
  return `
4. RIGHTS AND OBLIGATIONS

4.1 INVESTOR RIGHTS
(a) Receive distributions/dividends as per investment terms
(b) Access property performance reports quarterly
(c) Vote on governance proposals (equity tokens only)
(d) Transfer tokens subject to platform rules and regulations
(e) Receive audited annual property financial statements
(f) Inspect property with reasonable notice (equity tokens only)

4.2 PLATFORM OBLIGATIONS
PropChain shall:
(a) Manage property tokenization and smart contract deployment
(b) Facilitate dividend/distribution payments via blockchain
(c) Provide quarterly property performance updates
(d) Maintain proper accounting and tax records
(e) Ensure regulatory compliance with Nigerian laws
(f) Protect investor data per NDPC regulations

4.3 INVESTOR OBLIGATIONS
The Investor shall:
(a) Maintain valid KYC verification throughout investment period
(b) Report tax obligations to relevant Nigerian tax authorities
(c) Comply with platform terms of service
(d) Not engage in market manipulation or insider trading
(e) Maintain secure custody of wallet private keys
`;
}

export function getRiskDisclosures() {
  return `
5. RISK DISCLOSURE STATEMENT

The Investor acknowledges and accepts the following material risks:

5.1 MARKET RISK
Property values may decrease due to:
- Economic downturns affecting real estate markets
- Changes in neighborhood desirability
- Oversupply of similar properties
- Interest rate increases reducing property demand

5.2 LIQUIDITY RISK
- Tokens may not be easily sold or traded
- No guarantee of secondary market liquidity
- Early exit may result in selling below original investment amount
- Platform may restrict transfers pending regulatory approval

5.3 RENTAL INCOME RISK
- Rental income is not guaranteed
- Tenant defaults may reduce income
- Vacancy periods reduce returns
- Rental rates may decrease in market downturns

5.4 TECHNOLOGY RISK
- Blockchain smart contract vulnerabilities
- Hedera network disruptions or failures
- Wallet security breaches
- Platform technical failures affecting access

5.5 REGULATORY RISK
- Changes in Nigerian securities laws may affect investment
- Tax law changes may reduce net returns
- New regulations may restrict token trading
- Requirement to register as securities may impact liquidity

5.6 PLATFORM RISK
- PropChain business continuity not guaranteed
- Platform may cease operations
- Changes in platform fee structure
- Migration to new platform may be required

5.7 PROPERTY-SPECIFIC RISKS
- Physical damage from fire, flood, or natural disasters
- Structural defects not identified in inspection
- Environmental contamination liabilities
- Zoning law changes affecting property use
- Tenant damage beyond security deposits

5.8 CURRENCY RISK
- For investments denominated in Naira, currency devaluation risk
- Inflation may erode real returns
- Exchange rate fluctuations if converting to other currencies

THE INVESTOR CONFIRMS UNDERSTANDING THESE RISKS AND INVESTS VOLUNTARILY.
THIS IS A HIGH-RISK INVESTMENT. INVESTORS MAY LOSE ALL INVESTED CAPITAL.
PAST PERFORMANCE DOES NOT GUARANTEE FUTURE RESULTS.
`;
}

export function getNigerianCompliance() {
  return `
6. REGULATORY COMPLIANCE

This investment is conducted in accordance with the laws of the Federal Republic of Nigeria:

6.1 SECURITIES REGULATIONS
- Securities and Exchange Commission (SEC) Nigeria regulations
- Investment and Securities Act 2007
- SEC Rules on Digital Assets and Virtual Currencies
- Compliance with crowdfunding and alternative investment regulations

6.2 DATA PROTECTION
- Nigeria Data Protection Commission (NDPC) Regulations 2024
- Personal data processed per NDPC requirements
- Investor privacy rights protected
- Data retention and security measures implemented

6.3 CORPORATE LAW
- Companies and Allied Matters Act (CAMA) 2020 compliance
- Proper corporate governance structures
- Shareholder rights protection mechanisms
- Disclosure requirements adherence

6.4 ANTI-MONEY LAUNDERING
- Money Laundering (Prevention and Prohibition) Act 2022
- Know Your Customer (KYC) procedures per CBN guidelines
- Customer Due Diligence (CDD) standards
- Suspicious transaction reporting obligations

6.5 TAX OBLIGATIONS
- Investor responsible for reporting investment income to FIRS
- Withholding tax may apply to dividend distributions
- Capital gains tax may apply on token sale
- Professional tax advice recommended

PropChain maintains [registration/licensing] with relevant Nigerian regulatory authorities.
Investors should seek independent legal and tax advice before investing.
`;
}

export function getDisputeResolution() {
  return `
7. DISPUTE RESOLUTION

7.1 GOVERNING LAW
This Agreement is governed by the laws of the Federal Republic of Nigeria.

7.2 JURISDICTION
The parties submit to the exclusive jurisdiction of the Federal High Court of Nigeria sitting in Lagos.

7.3 ARBITRATION
Before court proceedings, parties agree to attempt resolution through:
(a) Direct negotiation between parties (30 days)
(b) Mediation facilitated by Lagos Chamber of Commerce (30 days)
(c) Arbitration under Nigerian Arbitration and Conciliation Act
    - Arbitration venue: Lagos, Nigeria
    - Arbitrator appointed per Lagos Court of Arbitration rules
    - Arbitration decision is final and binding

7.4 COSTS
Each party bears own legal costs unless arbitrator/court orders otherwise.
Platform may deduct dispute-related costs from investor distributions if investor claim is dismissed as frivolous.

7.5 CLASS ACTION WAIVER
Investor waives right to participate in class action lawsuits and agrees to pursue claims individually only.
`;
}

export function getGeneralProvisions() {
  return `
8. GENERAL PROVISIONS

8.1 AMENDMENTS
This Agreement may only be amended by written agreement of both parties.
Platform may update terms for new investments with 30 days notice via email and platform posting.

8.2 NOTICES
All notices shall be sent to:
- Platform: info@propchain.com
- Investor: Email address registered in investor account

Notices deemed received 24 hours after email sent or 7 days after postal mail.

8.3 SEVERABILITY
If any provision is held invalid or unenforceable, remaining provisions continue in full force.
Invalid provisions shall be replaced with valid provisions closest to original intent.

8.4 ENTIRE AGREEMENT
This Agreement constitutes entire agreement between parties.
Supersedes all prior negotiations, representations, and agreements.
No oral modifications permitted.

8.5 ASSIGNMENT
Investor may not assign rights under this Agreement except via platform token transfer mechanism.
Platform may assign rights with 60 days notice to investors.

8.6 FORCE MAJEURE
Neither party liable for failure to perform due to circumstances beyond reasonable control including:
- Acts of God, war, terrorism, civil unrest
- Government actions, legislation changes
- Blockchain network failures beyond platform control
- Internet infrastructure failures

8.7 SURVIVORSHIP
Provisions relating to confidentiality, dispute resolution, and liability limitations survive Agreement termination.

8.8 ELECTRONIC SIGNATURES
Parties agree electronic signatures via platform constitute legally binding acceptance.
Timestamps and IP addresses recorded for verification.
`;
}

export function formatNaira(amount: number): string {
  return `₦${amount.toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function formatDate(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-GB'); // DD/MM/YYYY format
}

export function formatTokenAmount(amount: number): string {
  return amount.toLocaleString('en-NG');
}
