import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabaseService } from "@/services/supabaseService";
import { toast } from "sonner";
import { useAuth } from "@/context/AuthContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  HoverCard,
  HoverCardContent,
  HoverCardTrigger,
} from "@/components/ui/hover-card";
import { Progress } from "@/components/ui/progress";
import { Separator } from "@/components/ui/separator";
import MoneyInput from "@/components/ui/money-input";
import TokenizationTermsAcceptance from "@/components/TokenizationTermsAcceptance";
import {
  ArrowLeft,
  Building,
  Banknote,
  TrendingUp,
  Info,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
  DollarSign,
} from "lucide-react";

// Tokenization types
type TokenizationType = "equity" | "debt" | "revenue";

interface TokenizationTypeOption {
  id: TokenizationType;
  title: string;
  description: string;
  icon: React.ComponentType<any>;
  badge: string;
  details: {
    structure: string;
    returns: string;
    risk: string;
    rights: string;
    example: string;
    maxRaise: string;
  };
}

const tokenizationTypes: TokenizationTypeOption[] = [
  {
    id: "equity",
    title: "Equity-Based Tokenization",
    description: "Fractional ownership of the property",
    icon: Building,
    badge: "Ownership",
    details: {
      structure: "Tokens represent actual shares/ownership of the property",
      returns: "Capital appreciation + proportional rental income/profits",
      risk: "Higher risk, higher potential reward",
      rights: "Voting rights on property decisions, ownership benefits",
      example:
        "Own 1% of property → get 1% of rental income + 1% of sale proceeds",
      maxRaise: "Maximum raise equals property appraised value",
    },
  },
  {
    id: "debt",
    title: "Debt-Based Tokenization",
    description: "Real estate-backed debt instrument",
    icon: Banknote,
    badge: "Lending",
    details: {
      structure: "Tokens represent loans to the property owner/developer",
      returns: "Fixed interest rate payments over time",
      risk: "Lower risk, predictable returns with LTV protection",
      rights: "Priority in repayment, no ownership or voting rights",
      example: "Lend at 8% annual interest with 70% LTV ratio protection",
      maxRaise: "Raise can be 70-80% of property value (LTV ratio)",
    },
  },
  {
    id: "revenue",
    title: "Revenue-Sharing Tokenization",
    description: "Share in property revenue streams",
    icon: TrendingUp,
    badge: "Revenue",
    details: {
      structure: "Tokens provide share of gross rental income/revenues",
      returns: "Percentage of property revenues (not profits)",
      risk: "Medium risk, income-focused without ownership",
      rights: "Revenue sharing without ownership obligations",
      example: "Receive 5% of all rental income generated by property",
      maxRaise: "Based on expected future cashflows (NPV/IRR models)",
    },
  },
];

const createTokenizationSchema = (propertyValue: number) =>
  z
    .object({
      tokenization_type: z.enum(["equity", "debt", "revenue"]),
      token_name: z.string().min(1, "Token name is required"),
      token_symbol: z
        .string()
        .min(2, "Token symbol must be at least 2 characters")
        .max(10, "Token symbol must be at most 10 characters"),
      total_supply: z
        .number()
        .min(1000, "Minimum total supply is 1,000 tokens"),
      price_per_token: z
        .number()
        .min(0.01, "Price per token must be at least 0.01"),
      min_investment: z.number().min(1, "Minimum investment is required"),
      max_investment: z.number().optional(),
      min_tokens_per_purchase: z.number().int().min(1).optional(),
      max_tokens_per_purchase: z.number().int().min(1).optional(),
      target_raise: z.number().min(1, "Target raise is required"),
      minimum_raise: z.number().min(1, "Minimum raise is required"),
      investment_window_days: z
        .number()
        .min(1, "Investment window must be at least 1 day")
        .max(365, "Investment window cannot exceed 365 days"),
      expected_roi_annual: z.number().min(0).max(100).optional(),
      dividend_frequency: z
        .enum(["monthly", "quarterly", "annually"])
        .optional(),
      management_fee_percentage: z.number().min(0).max(10).optional(),
      platform_fee_percentage: z.number().min(0).max(5).optional(),
      auto_refund: z.boolean().optional(),
    })
    .refine(
      (data) => {
        const maxPossibleRaise = data.total_supply * data.price_per_token;
        return data.target_raise <= maxPossibleRaise;
      },
      {
        message: "Target raise cannot exceed total supply × price per token",
        path: ["target_raise"],
      }
    )
    .refine(
      (data) => {
        // Minimum raise must be less than target raise
        return data.minimum_raise < data.target_raise;
      },
      {
        message: "Minimum raise must be less than target raise",
        path: ["minimum_raise"],
      }
    )
    .refine(
      (data) => {
        // Type-specific validation for target raise
        if (data.tokenization_type === "equity") {
          return data.target_raise <= propertyValue;
        } else if (data.tokenization_type === "debt") {
          // For debt, typically 70-80% LTV ratio
          const maxDebtRaise = propertyValue * 0.8;
          return data.target_raise <= maxDebtRaise;
        }
        // For revenue sharing, we allow more flexibility based on projected cashflows
        return true;
      },
      {
        message:
          "Target raise exceeds the allowed limit for this tokenization type",
        path: ["target_raise"],
      }
    )
    .refine(
      (data) => {
        // Validate that total token value doesn't exceed tokenization type limits
        const maxPossibleRaise = data.total_supply * data.price_per_token;
        
        if (data.tokenization_type === "equity") {
          // Equity can't exceed 100% of property value
          return maxPossibleRaise <= propertyValue;
        } else if (data.tokenization_type === "debt") {
          // Debt can't exceed 80% LTV ratio
          const maxDebtValue = propertyValue * 0.8;
          return maxPossibleRaise <= maxDebtValue;
        } else if (data.tokenization_type === "revenue") {
          // Revenue sharing - allow up to 2x property value for flexibility
          const maxRevenueValue = propertyValue * 2;
          return maxPossibleRaise <= maxRevenueValue;
        }
        return true;
      },
      {
        message: "Total token value (supply × price) exceeds the allowed limit for this tokenization type",
        path: ["total_supply"],
      }
    )
    .refine(
      (data) => {
        // Validate that max_investment >= min_investment
        if (data.max_investment) {
          return data.max_investment >= data.min_investment;
        }
        return true;
      },
      {
        message: "Maximum investment must be greater than or equal to minimum investment",
        path: ["max_investment"],
      }
    );

type TokenizationForm = z.infer<ReturnType<typeof createTokenizationSchema>>;

const TokenizeProperty = () => {
  const { propertyId } = useParams<{ propertyId: string }>();
  const navigate = useNavigate();
  const { user, isAuthenticated } = useAuth();
  const queryClient = useQueryClient();

  const [step, setStep] = useState(0); // Start with type selection
  const [selectedType, setSelectedType] = useState<TokenizationType>("equity");

  // Fetch property details
  const { data: property, isLoading: propertyLoading } = useQuery({
    queryKey: ["property", propertyId],
    queryFn: () => supabaseService.properties.getPropertyById(propertyId!),
    enabled: !!propertyId,
  });

  const form = useForm<TokenizationForm>({
    resolver: zodResolver(
      createTokenizationSchema(property?.estimated_value || 0)
    ),
    defaultValues: {
      tokenization_type: "equity" as TokenizationType,
      token_name: property ? `${property.title} Token` : "",
      token_symbol: property
        ? property.title
            .substring(0, 6)
            .toUpperCase()
            .replace(/[^A-Z]/g, "")
        : "",
      total_supply: 10000,
      price_per_token: 100,
      min_investment: 10000,
      max_investment: 1000000,
      target_raise: property
        ? Math.min(
            Math.floor((property.estimated_value || 0) * 0.8),
            property.estimated_value || 0
          )
        : 0,
      minimum_raise: property
        ? Math.floor((property.estimated_value || 0) * 0.3)
        : 0,
      min_tokens_per_purchase: 1,
      max_tokens_per_purchase: 1000,
      investment_window_days: 30,
      expected_roi_annual: 8,
      dividend_frequency: "quarterly",
      management_fee_percentage: 2.5,
      platform_fee_percentage: 1.0,
      auto_refund: true,
    },
  });

  // Watch form values for real-time calculations
  const totalSupply = form.watch("total_supply");
  const pricePerToken = form.watch("price_per_token");
  const maxPossibleRaise =
    totalSupply && pricePerToken ? totalSupply * pricePerToken : 0;

  const createTokenizationMutation = useMutation({
    mutationFn: async (data: TokenizationForm) => {
      if (!isAuthenticated || !user?.id) {
        throw new Error("You must be logged in to tokenize a property.");
      }
      if (!property || property.owner_id !== user.id) {
        throw new Error("You can only tokenize properties you own.");
      }

      const {
        investment_window_days,
        max_investment,
        expected_roi_annual,
        dividend_frequency,
        management_fee_percentage,
        platform_fee_percentage,
        auto_refund,
        tokenization_type,
        ...rest
      } = data;

      const now = new Date();
      const investment_window_start = now.toISOString();
      const investment_window_end = new Date(
        now.getTime() + investment_window_days * 24 * 60 * 60 * 1000
      ).toISOString();

      const selectedTypeInfo = tokenizationTypes.find(
        (t) => t.id === tokenization_type
      );
      const payload = {
        property_id: property.id,
        tokenization_type: tokenization_type,
        token_name: `${String(rest.token_name).trim()} (${
          selectedTypeInfo?.badge
        })`,
        token_symbol: String(rest.token_symbol).trim().toUpperCase(),
        total_supply: rest.total_supply,
        price_per_token: rest.price_per_token,
        min_investment: rest.min_investment,
        max_investment: max_investment || null,
        min_tokens_per_purchase: rest.min_tokens_per_purchase || null,
        max_tokens_per_purchase: rest.max_tokens_per_purchase || null,
        target_raise: rest.target_raise,
        minimum_raise: rest.minimum_raise,
        investment_window_start,
        investment_window_end,
        expected_roi_annual: expected_roi_annual || null,
        dividend_frequency: dividend_frequency || null,
        management_fee_percentage: management_fee_percentage || null,
        platform_fee_percentage: platform_fee_percentage || null,
        auto_refund: auto_refund ?? true,
        status: "draft",
      };

      return supabaseService.tokenizations.create(payload);
    },
    onSuccess: () => {
      toast.success("Tokenization created successfully");
      queryClient.invalidateQueries({ queryKey: ["property", propertyId] });
      navigate("/property/management");
    },
    onError: (error: any) => {
      const details = error?.details || error?.message || "Unknown error";
      const hint = error?.hint ? ` ${error.hint}` : "";
      const code = error?.code ? ` [${error.code}]` : "";
      toast.error(`Failed to create tokenization: ${details}${hint}${code}`);
    },
  });

  const handleTermsAccept = () => {
    form.handleSubmit(onSubmit)();
  };

  const handleTermsDecline = () => {
    setStep(2);
  };

  const handleTypeSelection = (type: TokenizationType) => {
    setSelectedType(type);
    form.setValue("tokenization_type", type);

    // Set type-specific default values
    if (type === "equity") {
      form.setValue(
        "target_raise",
        property ? Math.floor(property.estimated_value * 0.8) : 0
      );
      form.setValue(
        "minimum_raise",
        property ? Math.floor(property.estimated_value * 0.3) : 0
      );
    } else if (type === "debt") {
      form.setValue(
        "target_raise",
        property ? Math.floor(property.estimated_value * 0.7) : 0
      );
      form.setValue(
        "minimum_raise",
        property ? Math.floor(property.estimated_value * 0.5) : 0
      );
    } else if (type === "revenue") {
      form.setValue(
        "target_raise",
        property ? Math.floor(property.estimated_value * 0.5) : 0
      );
      form.setValue(
        "minimum_raise",
        property ? Math.floor(property.estimated_value * 0.25) : 0
      );
    }

    setStep(1);
  };

  const nextStep = async (e?: React.MouseEvent) => {
    console.log("🔄 nextStep called, current step:", step);
    
    // Prevent any form submission
    if (e) {
      e.preventDefault();
      e.stopPropagation();
    }
    
    const isValid = await form.trigger([
      "token_name",
      "token_symbol",
      "total_supply",
      "price_per_token",
    ]);

    console.log("Form validation result:", isValid);
    
    if (isValid) {
      console.log("✅ Setting step to 2");
      setStep(2);
    } else {
      console.log("❌ Form validation failed, staying on step 1");
    }
  };

  const prevStep = () => {
    if (step === 1) {
      setStep(0);
    } else {
      setStep(1);
    }
  };

  const onSubmit = (data: TokenizationForm) => {
    console.log("🚨 onSubmit called with step:", step);
    console.log("🚨 Form data:", data);
    
    // STRICT guard - only allow submission on the final step (step 2)
    if (step !== 2) {
      console.log("🚨 BLOCKED - not on final step. Current step:", step);
      toast.error(`Cannot submit on step ${step}. Please complete all steps first.`);
      return;
    }
    
    console.log("✅ Step check passed, proceeding with submission...");
    
    if (!isAuthenticated || !user?.id) {
      toast.error("Please log in to continue.");
      return;
    }
    if (!property || property.owner_id !== user.id) {
      toast.error("You can only tokenize your own property.");
      return;
    }
    
    console.log("🚀 Creating tokenization...");
    createTokenizationMutation.mutate(data);
  };

  if (propertyLoading) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          <div className="animate-pulse space-y-4">
            <div className="h-8 bg-muted rounded w-1/3"></div>
            <div className="h-4 bg-muted rounded w-2/3"></div>
            <div className="h-64 bg-muted rounded"></div>
          </div>
        </div>
      </div>
    );
  }

  if (!property) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-2xl font-bold mb-4">Property Not Found</h1>
          <Button onClick={() => navigate("/property/management")}>
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Properties
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <Button
            variant="ghost"
            onClick={() => navigate("/property/management")}
            className="mb-4 border-2 border-primary"
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to Management
          </Button>

          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold mb-2">Tokenize Property</h1>
              <p className="text-muted-foreground">
                {step === 0
                  ? "Choose your tokenization type"
                  : `Step ${step} of 3 - Configure your tokenization`}
              </p>
            </div>
            <div className="text-right">
              <p className="text-sm text-muted-foreground">Property Value</p>
              <p className="text-2xl font-bold">
                ₦{property.estimated_value.toLocaleString()}
              </p>
            </div>
          </div>

          <Progress
            value={step === 0 ? 0 : (step / 3) * 100}
            className="w-full mt-4"
          />
        </div>

        {/* Property Summary */}
        <Card className="mb-8">
          <CardContent className="p-6">
            <div className="flex items-center gap-4">
              <div className="w-20 h-20 bg-muted rounded-lg flex items-center justify-center">
                <Building className="h-8 w-8 text-muted-foreground" />
              </div>
              <div className="flex-1">
                <h3 className="font-semibold text-md truncate">{property.title}</h3>
                <p className="text-muted-foreground truncate text-sm">
                  {(property.location as any)?.address}, {(property.location as any)?.city}
                </p>
                <div className="flex items-center gap-4 mt-2">
                  <Badge variant="outline">{property.property_type}</Badge>
                  <Badge
                    variant={
                      property.approval_status === "approved"
                        ? "default"
                        : "secondary"
                    }
                  >
                    {property.approval_status}
                  </Badge>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-muted-foreground">Monthly Income</p>
                <p className="font-semibold">
                  ₦{property.rental_income_monthly?.toLocaleString() || "0"}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Main Content */}
        <Card>
          <CardContent className="p-6">
            <Form {...form}>
              <form
                onSubmit={(e) => {
                  e.preventDefault();
                  if (step === 2) {
                    form.handleSubmit(onSubmit)(e);
                  }
                }}
                className="space-y-6"
              >
                {step === 0 && (
                  <div className="space-y-6">
                    <div className="text-center mb-6">
                      <h2 className="text-2xl font-bold mb-2">
                        Choose Tokenization Type
                      </h2>
                      <p className="text-muted-foreground">
                        Select the type of tokenization that best fits your
                        investment strategy
                      </p>
                    </div>

                    <div className="space-y-4">
                      {tokenizationTypes.map((type) => {
                        const Icon = type.icon;
                        return (
                          <HoverCard key={type.id}>
                            <HoverCardTrigger asChild>
                              <Card
                                className="cursor-pointer hover:shadow-md transition-shadow border-2 hover:border-primary/50"
                                onClick={() => handleTypeSelection(type.id)}
                              >
                                <CardContent className="p-6">
                                  <div className="flex items-center gap-4">
                                    <div className="p-4 bg-primary/10 rounded-full">
                                      <Icon className="h-8 w-8 text-primary" />
                                    </div>
                                    <div className="flex-1">
                                      <div className="flex items-center gap-2 mb-2">
                                        <h4 className="font-semibold text-lg">
                                          {type.title}
                                        </h4>
                                        <Badge variant="secondary">
                                          {type.badge}
                                        </Badge>
                                      </div>
                                      <p className="text-muted-foreground">
                                        {type.description}
                                      </p>
                                    </div>
                                    <div className="flex items-center text-muted-foreground">
                                      <Info className="h-5 w-5" />
                                    </div>
                                  </div>
                                </CardContent>
                              </Card>
                            </HoverCardTrigger>
                            <HoverCardContent className="w-96" side="left">
                              <div className="space-y-4">
                                <div className="flex items-center gap-2">
                                  <Icon className="h-5 w-5 text-primary" />
                                  <h4 className="font-semibold">
                                    {type.title}
                                  </h4>
                                </div>

                                <div className="space-y-3 text-sm">
                                  <div>
                                    <p className="font-medium text-muted-foreground flex items-center gap-2">
                                      <Building className="h-4 w-4" />
                                      Structure:
                                    </p>
                                    <p className="text-xs">{type.details.structure}</p>
                                  </div>

                                  <div>
                                    <p className="font-medium text-muted-foreground flex items-center gap-2">
                                      <TrendingUp className="h-4 w-4" />
                                      Returns:
                                    </p>
                                    <p className="text-xs">{type.details.returns}</p>
                                  </div>

                                  <div>
                                    <p className="font-medium text-muted-foreground flex items-center gap-2">
                                      <AlertTriangle className="h-4 w-4" />
                                      Risk Level:
                                    </p>
                                    <p className="text-xs">{type.details.risk}</p>
                                  </div>

                                  <div>
                                    <p className="font-medium text-muted-foreground flex items-center gap-2">
                                      <DollarSign className="h-4 w-4" />
                                      Max Raise:
                                    </p>
                                    <p className="text-xs">{type.details.maxRaise}</p>
                                  </div>

                                  <Separator />

                                  <div>
                                    <p className="font-medium text-muted-foreground flex items-center gap-2">
                                      <Info className="h-4 w-4" />
                                      Example:
                                    </p>
                                    <p className="text-xs">
                                      {type.details.example}
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </HoverCardContent>
                          </HoverCard>
                        );
                      })}
                    </div>
                  </div>
                )}

                {step === 1 && (
                  <div className="space-y-6">
                    <div className="flex items-center justify-between">
                      <div>
                        <h2 className="text-2xl font-bold">
                          Basic Token Information
                        </h2>
                        <div className="flex items-center gap-2 mt-1">
                          <span className="text-sm text-muted-foreground">
                            Type:
                          </span>
                          <Badge variant="secondary">
                            {
                              tokenizationTypes.find(
                                (t) => t.id === selectedType
                              )?.badge
                            }
                          </Badge>
                        </div>
                      </div>
                      <Button
                        type="button"
                        variant="outline"
                        onClick={() => setStep(0)}
                      >
                        Change Type
                      </Button>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <FormField
                        control={form.control}
                        name="token_name"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Token Name</FormLabel>
                            <FormControl>
                              <Input
                                {...field}
                                placeholder="e.g., Luxury Apartment Token"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="token_symbol"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Token Symbol</FormLabel>
                            <FormControl>
                              <Input
                                {...field}
                                placeholder="e.g., LAT"
                                maxLength={10}
                              />
                            </FormControl>
                            <FormDescription>
                              2-10 characters, letters only
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <FormField
                        control={form.control}
                        name="total_supply"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Total Token Supply</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                {...field}
                                onChange={(e) =>
                                  field.onChange(Number(e.target.value))
                                }
                                placeholder="10000"
                              />
                            </FormControl>
                            <FormDescription>
                              Number of tokens to create
                              {pricePerToken > 0 && (
                                <span className="block text-xs mt-1">
                                  Max raise: ₦
                                  {(
                                    field.value * pricePerToken
                                  ).toLocaleString()}
                                </span>
                              )}
                              {property && (
                                <span className="block text-xs text-muted-foreground mt-1">
                                  {selectedType === "equity" &&
                                    `Equity limit: Max token value ≤ ₦${property.estimated_value?.toLocaleString()}`}
                                  {selectedType === "debt" &&
                                    `Debt limit: Max token value ≤ ₦${(
                                      property.estimated_value * 0.8
                                    ).toLocaleString()} (80% LTV)`}
                                  {selectedType === "revenue" &&
                                    `Revenue limit: Max token value ≤ ₦${(
                                      property.estimated_value * 2
                                    ).toLocaleString()} (flexible)`}
                                </span>
                              )}
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="price_per_token"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Price Per Token</FormLabel>
                            <FormControl>
                              <MoneyInput
                                value={field.value}
                                onChange={field.onChange}
                                placeholder="100"
                              />
                            </FormControl>
                            <FormDescription>
                              {totalSupply > 0 && (
                                <span className="text-xs">
                                  Max raise: ₦
                                  {(totalSupply * field.value).toLocaleString()}
                                </span>
                              )}
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                  </div>
                )}

            {step === 3 && selectedType && (
              <TokenizationTermsAcceptance
                tokenizationType={selectedType}
                tokenName={form.watch("token_name")}
                totalSupply={form.watch("total_supply")}
                onAccept={handleTermsAccept}
                onDecline={handleTermsDecline}
                isSubmitting={createTokenizationMutation.isPending}
              />
            )}

            {step === 2 && (
                  <div className="space-y-6">
                    <div>
                      <h2 className="text-2xl font-bold">Investment Details</h2>
                      <div className="flex items-center gap-2 mt-1">
                        <span className="text-sm text-muted-foreground">
                          Type:
                        </span>
                        <Badge variant="secondary">
                          {
                            tokenizationTypes.find((t) => t.id === selectedType)
                              ?.badge
                          }
                        </Badge>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <FormField
                        control={form.control}
                        name="target_raise"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Target Raise</FormLabel>
                            <FormControl>
                              <MoneyInput
                                value={field.value}
                                onChange={field.onChange}
                                placeholder="1000000"
                              />
                            </FormControl>
                            <FormDescription>
                              Goal amount to raise
                              {maxPossibleRaise > 0 && (
                                <span className="block text-xs mt-1">
                                  Token limit: ₦
                                  {maxPossibleRaise.toLocaleString()} (
                                  {totalSupply?.toLocaleString()} tokens × ₦
                                  {pricePerToken?.toLocaleString()})
                                </span>
                              )}
                              <span className="block text-xs text-muted-foreground">
                                {selectedType === "equity" &&
                                  `Max (Equity): ₦${property?.estimated_value?.toLocaleString()}`}
                                {selectedType === "debt" &&
                                  `Max (Debt 80% LTV): ₦${(
                                    (property?.estimated_value || 0) * 0.8
                                  ).toLocaleString()}`}
                                {selectedType === "revenue" &&
                                  `Max (Revenue): Based on cashflow projections`}
                              </span>
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="minimum_raise"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Minimum Raise</FormLabel>
                            <FormControl>
                              <MoneyInput
                                value={field.value}
                                onChange={field.onChange}
                                placeholder="300000"
                              />
                            </FormControl>
                            <FormDescription>
                              Minimum amount needed to proceed
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                      <FormField
                        control={form.control}
                        name="min_investment"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Minimum Investment</FormLabel>
                            <FormControl>
                              <MoneyInput
                                value={field.value}
                                onChange={field.onChange}
                                placeholder="10000"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="max_investment"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Maximum Investment</FormLabel>
                            <FormControl>
                              <MoneyInput
                                value={field.value}
                                onChange={field.onChange}
                                placeholder="1000000"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="investment_window_days"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Investment Window (Days)</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                {...field}
                                onChange={(e) =>
                                  field.onChange(Number(e.target.value))
                                }
                                placeholder="30"
                              />
                            </FormControl>
                            <FormDescription>
                              How long investors can invest
                            </FormDescription>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <FormField
                        control={form.control}
                        name="expected_roi_annual"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Expected Annual ROI (%)</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                step="0.1"
                                {...field}
                                onChange={(e) =>
                                  field.onChange(Number(e.target.value))
                                }
                                placeholder="8"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="dividend_frequency"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Dividend Frequency</FormLabel>
                            <Select
                              onValueChange={field.onChange}
                              value={field.value}
                            >
                              <FormControl>
                                <SelectTrigger>
                                  <SelectValue placeholder="Select frequency" />
                                </SelectTrigger>
                              </FormControl>
                              <SelectContent>
                                <SelectItem value="monthly">Monthly</SelectItem>
                                <SelectItem value="quarterly">
                                  Quarterly
                                </SelectItem>
                                <SelectItem value="annually">
                                  Annually
                                </SelectItem>
                              </SelectContent>
                            </Select>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      <FormField
                        control={form.control}
                        name="management_fee_percentage"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Management Fee (%)</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                step="0.1"
                                {...field}
                                onChange={(e) =>
                                  field.onChange(Number(e.target.value))
                                }
                                placeholder="2.5"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />

                      <FormField
                        control={form.control}
                        name="platform_fee_percentage"
                        render={({ field }) => (
                          <FormItem>
                            <FormLabel>Platform Fee (%)</FormLabel>
                            <FormControl>
                              <Input
                                type="number"
                                step="0.1"
                                {...field}
                                onChange={(e) =>
                                  field.onChange(Number(e.target.value))
                                }
                                placeholder="1.0"
                              />
                            </FormControl>
                            <FormMessage />
                          </FormItem>
                        )}
                      />
                    </div>
                  </div>
                )}

                {/* Footer Buttons */}
                <div className="flex justify-between pt-6">
                  {step === 0 ? (
                    <Button
                      type="button"
                      variant="outline"
                      onClick={() => navigate("/property/management")}
                    >
                      Cancel
                    </Button>
                  ) : step === 1 ? (
                    <>
                      <Button
                        type="button"
                        variant="outline"
                        onClick={prevStep}
                      >
                        <ChevronLeft className="mr-2 h-4 w-4" />
                        Back to Types
                      </Button>
                      <Button 
                        type="button" 
                        onClick={(e) => {
                          e.preventDefault();
                          e.stopPropagation();
                          nextStep(e);
                        }}
                      >
                        Next Step
                        <ChevronRight className="ml-2 h-4 w-4" />
                      </Button>
                    </>
                  ) : (
                    <>
                      <Button
                        type="button"
                        variant="outline"
                        onClick={prevStep}
                      >
                        <ChevronLeft className="mr-2 h-4 w-4" />
                        Previous
                      </Button>
                      <Button
                        type="submit"
                        disabled={createTokenizationMutation.isPending}
                      >
                        {createTokenizationMutation.isPending
                          ? "Creating..."
                          : "Create Tokenization"}
                      </Button>
                    </>
                  )}
                </div>
              </form>
            </Form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default TokenizeProperty;
