/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DividendDistributor {
  export type DistributionStruct = {
    distributionId: BytesLike;
    tokenContract: AddressLike;
    totalAmount: BigNumberish;
    perTokenAmount: BigNumberish;
    snapshotBlock: BigNumberish;
    totalClaimed: BigNumberish;
    expiryDate: BigNumberish;
    active: boolean;
  };

  export type DistributionStructOutput = [
    distributionId: string,
    tokenContract: string,
    totalAmount: bigint,
    perTokenAmount: bigint,
    snapshotBlock: bigint,
    totalClaimed: bigint,
    expiryDate: bigint,
    active: boolean
  ] & {
    distributionId: string;
    tokenContract: string;
    totalAmount: bigint;
    perTokenAmount: bigint;
    snapshotBlock: bigint;
    totalClaimed: bigint;
    expiryDate: bigint;
    active: boolean;
  };
}

export interface DividendDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuthorizedCaller"
      | "authorizedCallers"
      | "batchDistribute"
      | "batchSetClaimableAmounts"
      | "claimDividend"
      | "claimableAmounts"
      | "createDistribution"
      | "distributions"
      | "getClaimableAmount"
      | "getDistribution"
      | "hasClaimed"
      | "hasClaimedDividend"
      | "owner"
      | "removeAuthorizedCaller"
      | "setClaimableAmount"
      | "withdrawUnclaimed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchDistributed"
      | "DistributionCreated"
      | "DistributionExpired"
      | "DividendClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuthorizedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchDistribute",
    values: [BytesLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetClaimableAmounts",
    values: [BytesLike, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmounts",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDistribution",
    values: [
      BytesLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "distributions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistribution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimedDividend",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimableAmount",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUnclaimed",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchDistribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetClaimableAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasClaimedDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUnclaimed",
    data: BytesLike
  ): Result;
}

export namespace BatchDistributedEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    recipientCount: BigNumberish,
    totalAmount: BigNumberish
  ];
  export type OutputTuple = [
    distributionId: string,
    recipientCount: bigint,
    totalAmount: bigint
  ];
  export interface OutputObject {
    distributionId: string;
    recipientCount: bigint;
    totalAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributionCreatedEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    totalAmount: BigNumberish,
    perTokenAmount: BigNumberish,
    snapshotBlock: BigNumberish
  ];
  export type OutputTuple = [
    distributionId: string,
    totalAmount: bigint,
    perTokenAmount: bigint,
    snapshotBlock: bigint
  ];
  export interface OutputObject {
    distributionId: string;
    totalAmount: bigint;
    perTokenAmount: bigint;
    snapshotBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributionExpiredEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    unclaimedAmount: BigNumberish
  ];
  export type OutputTuple = [distributionId: string, unclaimedAmount: bigint];
  export interface OutputObject {
    distributionId: string;
    unclaimedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendClaimedEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    distributionId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    distributionId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DividendDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): DividendDistributor;
  waitForDeployment(): Promise<this>;

  interface: DividendDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  batchDistribute: TypedContractMethod<
    [
      distributionId: BytesLike,
      recipients: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  batchSetClaimableAmounts: TypedContractMethod<
    [
      distributionId: BytesLike,
      holders: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  claimDividend: TypedContractMethod<
    [distributionId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimableAmounts: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  createDistribution: TypedContractMethod<
    [
      distributionId: BytesLike,
      tokenContract: AddressLike,
      totalAmount: BigNumberish,
      perTokenAmount: BigNumberish,
      snapshotBlock: BigNumberish,
      expiryDays: BigNumberish
    ],
    [void],
    "payable"
  >;

  distributions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        distributionId: string;
        tokenContract: string;
        totalAmount: bigint;
        perTokenAmount: bigint;
        snapshotBlock: bigint;
        totalClaimed: bigint;
        expiryDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  getClaimableAmount: TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;

  getDistribution: TypedContractMethod<
    [distributionId: BytesLike],
    [DividendDistributor.DistributionStructOutput],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasClaimedDividend: TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  setClaimableAmount: TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawUnclaimed: TypedContractMethod<
    [distributionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "batchDistribute"
  ): TypedContractMethod<
    [
      distributionId: BytesLike,
      recipients: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetClaimableAmounts"
  ): TypedContractMethod<
    [
      distributionId: BytesLike,
      holders: AddressLike[],
      amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimDividend"
  ): TypedContractMethod<[distributionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmounts"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createDistribution"
  ): TypedContractMethod<
    [
      distributionId: BytesLike,
      tokenContract: AddressLike,
      totalAmount: BigNumberish,
      perTokenAmount: BigNumberish,
      snapshotBlock: BigNumberish,
      expiryDays: BigNumberish
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "distributions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        distributionId: string;
        tokenContract: string;
        totalAmount: bigint;
        perTokenAmount: bigint;
        snapshotBlock: bigint;
        totalClaimed: bigint;
        expiryDate: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClaimableAmount"
  ): TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDistribution"
  ): TypedContractMethod<
    [distributionId: BytesLike],
    [DividendDistributor.DistributionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimedDividend"
  ): TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setClaimableAmount"
  ): TypedContractMethod<
    [distributionId: BytesLike, holder: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawUnclaimed"
  ): TypedContractMethod<[distributionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "BatchDistributed"
  ): TypedContractEvent<
    BatchDistributedEvent.InputTuple,
    BatchDistributedEvent.OutputTuple,
    BatchDistributedEvent.OutputObject
  >;
  getEvent(
    key: "DistributionCreated"
  ): TypedContractEvent<
    DistributionCreatedEvent.InputTuple,
    DistributionCreatedEvent.OutputTuple,
    DistributionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DistributionExpired"
  ): TypedContractEvent<
    DistributionExpiredEvent.InputTuple,
    DistributionExpiredEvent.OutputTuple,
    DistributionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "DividendClaimed"
  ): TypedContractEvent<
    DividendClaimedEvent.InputTuple,
    DividendClaimedEvent.OutputTuple,
    DividendClaimedEvent.OutputObject
  >;

  filters: {
    "BatchDistributed(bytes32,uint256,uint256)": TypedContractEvent<
      BatchDistributedEvent.InputTuple,
      BatchDistributedEvent.OutputTuple,
      BatchDistributedEvent.OutputObject
    >;
    BatchDistributed: TypedContractEvent<
      BatchDistributedEvent.InputTuple,
      BatchDistributedEvent.OutputTuple,
      BatchDistributedEvent.OutputObject
    >;

    "DistributionCreated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      DistributionCreatedEvent.InputTuple,
      DistributionCreatedEvent.OutputTuple,
      DistributionCreatedEvent.OutputObject
    >;
    DistributionCreated: TypedContractEvent<
      DistributionCreatedEvent.InputTuple,
      DistributionCreatedEvent.OutputTuple,
      DistributionCreatedEvent.OutputObject
    >;

    "DistributionExpired(bytes32,uint256)": TypedContractEvent<
      DistributionExpiredEvent.InputTuple,
      DistributionExpiredEvent.OutputTuple,
      DistributionExpiredEvent.OutputObject
    >;
    DistributionExpired: TypedContractEvent<
      DistributionExpiredEvent.InputTuple,
      DistributionExpiredEvent.OutputTuple,
      DistributionExpiredEvent.OutputObject
    >;

    "DividendClaimed(bytes32,address,uint256)": TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;
    DividendClaimed: TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;
  };
}
