/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GovernanceExecutor {
  export type ProposalStruct = {
    proposalId: BytesLike;
    propertyTreasury: AddressLike;
    budget: BigNumberish;
    proposalType: BigNumberish;
    votingEndTime: BigNumberish;
    status: BigNumberish;
    lockedAmount: BigNumberish;
    recipient: AddressLike;
    executedAt: BigNumberish;
  };

  export type ProposalStructOutput = [
    proposalId: string,
    propertyTreasury: string,
    budget: bigint,
    proposalType: bigint,
    votingEndTime: bigint,
    status: bigint,
    lockedAmount: bigint,
    recipient: string,
    executedAt: bigint
  ] & {
    proposalId: string;
    propertyTreasury: string;
    budget: bigint;
    proposalType: bigint;
    votingEndTime: bigint;
    status: bigint;
    lockedAmount: bigint;
    recipient: string;
    executedAt: bigint;
  };
}

export interface GovernanceExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuthorizedCaller"
      | "authorizedCallers"
      | "cancelProposal"
      | "executeProposal"
      | "getProposal"
      | "lockFundsForProposal"
      | "owner"
      | "proposals"
      | "registerProposal"
      | "releaseFunds"
      | "removeAuthorizedCaller"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsLocked"
      | "FundsReleased"
      | "ProposalCancelled"
      | "ProposalExecuted"
      | "ProposalRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuthorizedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockFundsForProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProposal",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseFunds",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedCaller",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockFundsForProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "releaseFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedCaller",
    data: BytesLike
  ): Result;
}

export namespace FundsLockedEvent {
  export type InputTuple = [proposalId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [proposalId: string, amount: bigint];
  export interface OutputObject {
    proposalId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsReleasedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    recipient: string,
    amount: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    amountRefunded: BigNumberish
  ];
  export type OutputTuple = [proposalId: string, amountRefunded: bigint];
  export interface OutputObject {
    proposalId: string;
    amountRefunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    amountReleased: BigNumberish
  ];
  export type OutputTuple = [proposalId: string, amountReleased: bigint];
  export interface OutputObject {
    proposalId: string;
    amountReleased: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRegisteredEvent {
  export type InputTuple = [
    proposalId: BytesLike,
    propertyTreasury: AddressLike,
    budget: BigNumberish,
    proposalType: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: string,
    propertyTreasury: string,
    budget: bigint,
    proposalType: bigint
  ];
  export interface OutputObject {
    proposalId: string;
    propertyTreasury: string;
    budget: bigint;
    proposalType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceExecutor;
  waitForDeployment(): Promise<this>;

  interface: GovernanceExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  cancelProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "nonpayable"
  >;

  executeProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "payable"
  >;

  getProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [GovernanceExecutor.ProposalStructOutput],
    "view"
  >;

  lockFundsForProposal: TypedContractMethod<
    [proposalId: BytesLike],
    [void],
    "payable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        proposalId: string;
        propertyTreasury: string;
        budget: bigint;
        proposalType: bigint;
        votingEndTime: bigint;
        status: bigint;
        lockedAmount: bigint;
        recipient: string;
        executedAt: bigint;
      }
    ],
    "view"
  >;

  registerProposal: TypedContractMethod<
    [
      proposalId: BytesLike,
      propertyTreasury: AddressLike,
      budget: BigNumberish,
      proposalType: BigNumberish,
      votingEndTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  releaseFunds: TypedContractMethod<
    [proposalId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  removeAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BytesLike],
    [GovernanceExecutor.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockFundsForProposal"
  ): TypedContractMethod<[proposalId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        proposalId: string;
        propertyTreasury: string;
        budget: bigint;
        proposalType: bigint;
        votingEndTime: bigint;
        status: bigint;
        lockedAmount: bigint;
        recipient: string;
        executedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProposal"
  ): TypedContractMethod<
    [
      proposalId: BytesLike,
      propertyTreasury: AddressLike,
      budget: BigNumberish,
      proposalType: BigNumberish,
      votingEndTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "releaseFunds"
  ): TypedContractMethod<
    [proposalId: BytesLike, recipient: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FundsLocked"
  ): TypedContractEvent<
    FundsLockedEvent.InputTuple,
    FundsLockedEvent.OutputTuple,
    FundsLockedEvent.OutputObject
  >;
  getEvent(
    key: "FundsReleased"
  ): TypedContractEvent<
    FundsReleasedEvent.InputTuple,
    FundsReleasedEvent.OutputTuple,
    FundsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRegistered"
  ): TypedContractEvent<
    ProposalRegisteredEvent.InputTuple,
    ProposalRegisteredEvent.OutputTuple,
    ProposalRegisteredEvent.OutputObject
  >;

  filters: {
    "FundsLocked(bytes32,uint256)": TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;
    FundsLocked: TypedContractEvent<
      FundsLockedEvent.InputTuple,
      FundsLockedEvent.OutputTuple,
      FundsLockedEvent.OutputObject
    >;

    "FundsReleased(bytes32,address,uint256)": TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;
    FundsReleased: TypedContractEvent<
      FundsReleasedEvent.InputTuple,
      FundsReleasedEvent.OutputTuple,
      FundsReleasedEvent.OutputObject
    >;

    "ProposalCancelled(bytes32,uint256)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "ProposalExecuted(bytes32,uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalRegistered(bytes32,address,uint256,uint8)": TypedContractEvent<
      ProposalRegisteredEvent.InputTuple,
      ProposalRegisteredEvent.OutputTuple,
      ProposalRegisteredEvent.OutputObject
    >;
    ProposalRegistered: TypedContractEvent<
      ProposalRegisteredEvent.InputTuple,
      ProposalRegisteredEvent.OutputTuple,
      ProposalRegisteredEvent.OutputObject
    >;
  };
}
