/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultiSigTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSigner"
      | "approveWithdrawal"
      | "cancelWithdrawal"
      | "deposit"
      | "executeWithdrawal"
      | "getBalance"
      | "getSigners"
      | "getWithdrawalRequest"
      | "hasApproved"
      | "nextRequestId"
      | "propertyOwner"
      | "removeSigner"
      | "requiredApprovals"
      | "signerList"
      | "signers"
      | "submitWithdrawal"
      | "updateThreshold"
      | "withdrawalRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsDeposited"
      | "SignerAdded"
      | "SignerRemoved"
      | "ThresholdUpdated"
      | "WithdrawalApproved"
      | "WithdrawalCancelled"
      | "WithdrawalExecuted"
      | "WithdrawalSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSigners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWithdrawalRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "propertyOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "signerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitWithdrawal",
    values: [BigNumberish, AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addSigner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWithdrawalRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "propertyOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signerList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "signers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;
}

export namespace FundsDepositedEvent {
  export type InputTuple = [sender: AddressLike, amount: BigNumberish];
  export type OutputTuple = [sender: string, amount: bigint];
  export interface OutputObject {
    sender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerRemovedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalApprovedEvent {
  export type InputTuple = [requestId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [requestId: bigint, approver: string];
  export interface OutputObject {
    requestId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalCancelledEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalExecutedEvent {
  export type InputTuple = [requestId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [requestId: bigint, amount: bigint];
  export interface OutputObject {
    requestId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalSubmittedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    recipient: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    requestId: bigint,
    recipient: string,
    amount: bigint,
    reason: string
  ];
  export interface OutputObject {
    requestId: bigint;
    recipient: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiSigTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): MultiSigTreasury;
  waitForDeployment(): Promise<this>;

  interface: MultiSigTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSigner: TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;

  approveWithdrawal: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelWithdrawal: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  executeWithdrawal: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[], [bigint], "view">;

  getSigners: TypedContractMethod<[], [string[]], "view">;

  getWithdrawalRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        amount: bigint;
        recipient: string;
        reason: string;
        requester: string;
        approvalCount: bigint;
        createdAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  hasApproved: TypedContractMethod<
    [requestId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;

  nextRequestId: TypedContractMethod<[], [bigint], "view">;

  propertyOwner: TypedContractMethod<[], [string], "view">;

  removeSigner: TypedContractMethod<
    [signer: AddressLike],
    [void],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  signerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  signers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  submitWithdrawal: TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;

  updateThreshold: TypedContractMethod<
    [newThreshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawalRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        requestId: bigint;
        amount: bigint;
        recipient: string;
        reason: string;
        requester: string;
        approvalCount: bigint;
        createdAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveWithdrawal"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelWithdrawal"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "executeWithdrawal"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSigners"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getWithdrawalRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, boolean, boolean] & {
        amount: bigint;
        recipient: string;
        reason: string;
        requester: string;
        approvalCount: bigint;
        createdAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<
    [requestId: BigNumberish, signer: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "propertyOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeSigner"
  ): TypedContractMethod<[signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "signerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "signers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitWithdrawal"
  ): TypedContractMethod<
    [amount: BigNumberish, recipient: AddressLike, reason: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateThreshold"
  ): TypedContractMethod<[newThreshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean
      ] & {
        requestId: bigint;
        amount: bigint;
        recipient: string;
        reason: string;
        requester: string;
        approvalCount: bigint;
        createdAt: bigint;
        executed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "FundsDeposited"
  ): TypedContractEvent<
    FundsDepositedEvent.InputTuple,
    FundsDepositedEvent.OutputTuple,
    FundsDepositedEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "SignerRemoved"
  ): TypedContractEvent<
    SignerRemovedEvent.InputTuple,
    SignerRemovedEvent.OutputTuple,
    SignerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdUpdated"
  ): TypedContractEvent<
    ThresholdUpdatedEvent.InputTuple,
    ThresholdUpdatedEvent.OutputTuple,
    ThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalApproved"
  ): TypedContractEvent<
    WithdrawalApprovedEvent.InputTuple,
    WithdrawalApprovedEvent.OutputTuple,
    WithdrawalApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalCancelled"
  ): TypedContractEvent<
    WithdrawalCancelledEvent.InputTuple,
    WithdrawalCancelledEvent.OutputTuple,
    WithdrawalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalExecuted"
  ): TypedContractEvent<
    WithdrawalExecutedEvent.InputTuple,
    WithdrawalExecutedEvent.OutputTuple,
    WithdrawalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalSubmitted"
  ): TypedContractEvent<
    WithdrawalSubmittedEvent.InputTuple,
    WithdrawalSubmittedEvent.OutputTuple,
    WithdrawalSubmittedEvent.OutputObject
  >;

  filters: {
    "FundsDeposited(address,uint256)": TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;
    FundsDeposited: TypedContractEvent<
      FundsDepositedEvent.InputTuple,
      FundsDepositedEvent.OutputTuple,
      FundsDepositedEvent.OutputObject
    >;

    "SignerAdded(address)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "SignerRemoved(address)": TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;
    SignerRemoved: TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;

    "ThresholdUpdated(uint256)": TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;
    ThresholdUpdated: TypedContractEvent<
      ThresholdUpdatedEvent.InputTuple,
      ThresholdUpdatedEvent.OutputTuple,
      ThresholdUpdatedEvent.OutputObject
    >;

    "WithdrawalApproved(uint256,address)": TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;
    WithdrawalApproved: TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;

    "WithdrawalCancelled(uint256)": TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;
    WithdrawalCancelled: TypedContractEvent<
      WithdrawalCancelledEvent.InputTuple,
      WithdrawalCancelledEvent.OutputTuple,
      WithdrawalCancelledEvent.OutputObject
    >;

    "WithdrawalExecuted(uint256,uint256)": TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;
    WithdrawalExecuted: TypedContractEvent<
      WithdrawalExecutedEvent.InputTuple,
      WithdrawalExecutedEvent.OutputTuple,
      WithdrawalExecutedEvent.OutputObject
    >;

    "WithdrawalSubmitted(uint256,address,uint256,string)": TypedContractEvent<
      WithdrawalSubmittedEvent.InputTuple,
      WithdrawalSubmittedEvent.OutputTuple,
      WithdrawalSubmittedEvent.OutputObject
    >;
    WithdrawalSubmitted: TypedContractEvent<
      WithdrawalSubmittedEvent.InputTuple,
      WithdrawalSubmittedEvent.OutputTuple,
      WithdrawalSubmittedEvent.OutputObject
    >;
  };
}
