/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PlatformEscrowManager {
  export type EscrowStruct = {
    tokenizationId: BytesLike;
    targetRaise: BigNumberish;
    minimumRaise: BigNumberish;
    currentRaise: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    investorCount: BigNumberish;
    propertyOwner: AddressLike;
  };

  export type EscrowStructOutput = [
    tokenizationId: string,
    targetRaise: bigint,
    minimumRaise: bigint,
    currentRaise: bigint,
    deadline: bigint,
    status: bigint,
    investorCount: bigint,
    propertyOwner: string
  ] & {
    tokenizationId: string;
    targetRaise: bigint;
    minimumRaise: bigint;
    currentRaise: bigint;
    deadline: bigint;
    status: bigint;
    investorCount: bigint;
    propertyOwner: string;
  };

  export type InvestmentStruct = {
    investmentId: BytesLike;
    tokenizationId: BytesLike;
    investor: AddressLike;
    amount: BigNumberish;
    refunded: boolean;
    timestamp: BigNumberish;
  };

  export type InvestmentStructOutput = [
    investmentId: string,
    tokenizationId: string,
    investor: string,
    amount: bigint,
    refunded: boolean,
    timestamp: bigint
  ] & {
    investmentId: string;
    tokenizationId: string;
    investor: string;
    amount: bigint;
    refunded: boolean;
    timestamp: bigint;
  };
}

export interface PlatformEscrowManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAuthorizedCaller"
      | "authorizedCallers"
      | "canClaimRefund"
      | "cancelEscrow"
      | "claimRefund"
      | "createEscrow"
      | "depositInvestment"
      | "escrowInvestments"
      | "escrows"
      | "finalizeEscrow"
      | "getEscrow"
      | "getInvestment"
      | "investments"
      | "owner"
      | "refundInvestors"
      | "removeAuthorizedCaller"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EscrowCancelled"
      | "EscrowCreated"
      | "EscrowFinalized"
      | "InvestmentDeposited"
      | "RefundIssued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAuthorizedCaller",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canClaimRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createEscrow",
    values: [BytesLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositInvestment",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowInvestments",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "escrows", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "finalizeEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEscrow",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "investments",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "refundInvestors",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedCaller",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addAuthorizedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canClaimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escrows", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEscrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "refundInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedCaller",
    data: BytesLike
  ): Result;
}

export namespace EscrowCancelledEvent {
  export type InputTuple = [tokenizationId: BytesLike];
  export type OutputTuple = [tokenizationId: string];
  export interface OutputObject {
    tokenizationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowCreatedEvent {
  export type InputTuple = [
    tokenizationId: BytesLike,
    targetRaise: BigNumberish,
    minimumRaise: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    tokenizationId: string,
    targetRaise: bigint,
    minimumRaise: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    tokenizationId: string;
    targetRaise: bigint;
    minimumRaise: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscrowFinalizedEvent {
  export type InputTuple = [
    tokenizationId: BytesLike,
    totalRaised: BigNumberish
  ];
  export type OutputTuple = [tokenizationId: string, totalRaised: bigint];
  export interface OutputObject {
    tokenizationId: string;
    totalRaised: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentDepositedEvent {
  export type InputTuple = [
    investmentId: BytesLike,
    tokenizationId: BytesLike,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: string,
    tokenizationId: string,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    investmentId: string;
    tokenizationId: string;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundIssuedEvent {
  export type InputTuple = [
    investmentId: BytesLike,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: string,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    investmentId: string;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlatformEscrowManager extends BaseContract {
  connect(runner?: ContractRunner | null): PlatformEscrowManager;
  waitForDeployment(): Promise<this>;

  interface: PlatformEscrowManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCallers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  canClaimRefund: TypedContractMethod<
    [investmentId: BytesLike],
    [boolean],
    "view"
  >;

  cancelEscrow: TypedContractMethod<
    [tokenizationId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<
    [investmentId: BytesLike],
    [void],
    "nonpayable"
  >;

  createEscrow: TypedContractMethod<
    [
      tokenizationId: BytesLike,
      targetRaise: BigNumberish,
      minimumRaise: BigNumberish,
      deadline: BigNumberish,
      propertyOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  depositInvestment: TypedContractMethod<
    [tokenizationId: BytesLike, investmentId: BytesLike, investor: AddressLike],
    [void],
    "payable"
  >;

  escrowInvestments: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  escrows: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        tokenizationId: string;
        targetRaise: bigint;
        minimumRaise: bigint;
        currentRaise: bigint;
        deadline: bigint;
        status: bigint;
        investorCount: bigint;
        propertyOwner: string;
      }
    ],
    "view"
  >;

  finalizeEscrow: TypedContractMethod<
    [tokenizationId: BytesLike],
    [void],
    "nonpayable"
  >;

  getEscrow: TypedContractMethod<
    [tokenizationId: BytesLike],
    [PlatformEscrowManager.EscrowStructOutput],
    "view"
  >;

  getInvestment: TypedContractMethod<
    [investmentId: BytesLike],
    [PlatformEscrowManager.InvestmentStructOutput],
    "view"
  >;

  investments: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint] & {
        investmentId: string;
        tokenizationId: string;
        investor: string;
        amount: bigint;
        refunded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  refundInvestors: TypedContractMethod<
    [tokenizationId: BytesLike],
    [void],
    "nonpayable"
  >;

  removeAuthorizedCaller: TypedContractMethod<
    [caller: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "canClaimRefund"
  ): TypedContractMethod<[investmentId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "cancelEscrow"
  ): TypedContractMethod<[tokenizationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[investmentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEscrow"
  ): TypedContractMethod<
    [
      tokenizationId: BytesLike,
      targetRaise: BigNumberish,
      minimumRaise: BigNumberish,
      deadline: BigNumberish,
      propertyOwner: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositInvestment"
  ): TypedContractMethod<
    [tokenizationId: BytesLike, investmentId: BytesLike, investor: AddressLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "escrowInvestments"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "escrows"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, bigint, bigint, bigint, bigint, string] & {
        tokenizationId: string;
        targetRaise: bigint;
        minimumRaise: bigint;
        currentRaise: bigint;
        deadline: bigint;
        status: bigint;
        investorCount: bigint;
        propertyOwner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeEscrow"
  ): TypedContractMethod<[tokenizationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEscrow"
  ): TypedContractMethod<
    [tokenizationId: BytesLike],
    [PlatformEscrowManager.EscrowStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvestment"
  ): TypedContractMethod<
    [investmentId: BytesLike],
    [PlatformEscrowManager.InvestmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "investments"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, boolean, bigint] & {
        investmentId: string;
        tokenizationId: string;
        investor: string;
        amount: bigint;
        refunded: boolean;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "refundInvestors"
  ): TypedContractMethod<[tokenizationId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAuthorizedCaller"
  ): TypedContractMethod<[caller: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EscrowCancelled"
  ): TypedContractEvent<
    EscrowCancelledEvent.InputTuple,
    EscrowCancelledEvent.OutputTuple,
    EscrowCancelledEvent.OutputObject
  >;
  getEvent(
    key: "EscrowCreated"
  ): TypedContractEvent<
    EscrowCreatedEvent.InputTuple,
    EscrowCreatedEvent.OutputTuple,
    EscrowCreatedEvent.OutputObject
  >;
  getEvent(
    key: "EscrowFinalized"
  ): TypedContractEvent<
    EscrowFinalizedEvent.InputTuple,
    EscrowFinalizedEvent.OutputTuple,
    EscrowFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentDeposited"
  ): TypedContractEvent<
    InvestmentDepositedEvent.InputTuple,
    InvestmentDepositedEvent.OutputTuple,
    InvestmentDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RefundIssued"
  ): TypedContractEvent<
    RefundIssuedEvent.InputTuple,
    RefundIssuedEvent.OutputTuple,
    RefundIssuedEvent.OutputObject
  >;

  filters: {
    "EscrowCancelled(bytes32)": TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;
    EscrowCancelled: TypedContractEvent<
      EscrowCancelledEvent.InputTuple,
      EscrowCancelledEvent.OutputTuple,
      EscrowCancelledEvent.OutputObject
    >;

    "EscrowCreated(bytes32,uint256,uint256,uint256)": TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;
    EscrowCreated: TypedContractEvent<
      EscrowCreatedEvent.InputTuple,
      EscrowCreatedEvent.OutputTuple,
      EscrowCreatedEvent.OutputObject
    >;

    "EscrowFinalized(bytes32,uint256)": TypedContractEvent<
      EscrowFinalizedEvent.InputTuple,
      EscrowFinalizedEvent.OutputTuple,
      EscrowFinalizedEvent.OutputObject
    >;
    EscrowFinalized: TypedContractEvent<
      EscrowFinalizedEvent.InputTuple,
      EscrowFinalizedEvent.OutputTuple,
      EscrowFinalizedEvent.OutputObject
    >;

    "InvestmentDeposited(bytes32,bytes32,address,uint256)": TypedContractEvent<
      InvestmentDepositedEvent.InputTuple,
      InvestmentDepositedEvent.OutputTuple,
      InvestmentDepositedEvent.OutputObject
    >;
    InvestmentDeposited: TypedContractEvent<
      InvestmentDepositedEvent.InputTuple,
      InvestmentDepositedEvent.OutputTuple,
      InvestmentDepositedEvent.OutputObject
    >;

    "RefundIssued(bytes32,address,uint256)": TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
    RefundIssued: TypedContractEvent<
      RefundIssuedEvent.InputTuple,
      RefundIssuedEvent.OutputTuple,
      RefundIssuedEvent.OutputObject
    >;
  };
}
