// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjtqptljuggbymcoovey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdHFwdGxqdWdnYnltY29vdmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Mzc3NTMsImV4cCI6MjA3NDAxMzc1M30.DahSaLwtBP00L_hG0xRrU5MfBxYN6Hk96jBC_z1o-7o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});